package sop_corba;


/**
* sop_corba/GestionPersonal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public interface GestionPersonal extends GestionPersonalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPersonal
