package sop_corba;


/**
* sop_corba/GestionPersonalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public interface GestionPersonalOperations 
{
  void registrarPersonal (sop_corba.GestionPersonalPackage.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res);
  boolean consultarPersonal (int id, sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal);
} // interface GestionPersonalOperations
