package sop_corba;


/**
* sop_corba/GestionPersonalPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public abstract class GestionPersonalPOA extends org.omg.PortableServer.Servant
 implements sop_corba.GestionPersonalOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarPersonal", new java.lang.Integer (0));
    _methods.put ("consultarPersonal", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionPersonal/registrarPersonal
       {
         sop_corba.GestionPersonalPackage.personalDTO objPersonal = sop_corba.GestionPersonalPackage.personalDTOHelper.read (in);
         org.omg.CORBA.BooleanHolder res = new org.omg.CORBA.BooleanHolder ();
         this.registrarPersonal (objPersonal, res);
         out = $rh.createReply();
         out.write_boolean (res.value);
         break;
       }

       case 1:  // sop_corba/GestionPersonal/consultarPersonal
       {
         int id = in.read_long ();
         sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal = new sop_corba.GestionPersonalPackage.personalDTOHolder ();
         boolean $result = false;
         $result = this.consultarPersonal (id, objPersonal);
         out = $rh.createReply();
         out.write_boolean ($result);
         sop_corba.GestionPersonalPackage.personalDTOHelper.write (out, objPersonal.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPersonal:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionPersonal _this() 
  {
    return GestionPersonalHelper.narrow(
    super._this_object());
  }

  public GestionPersonal _this(org.omg.CORBA.ORB orb) 
  {
    return GestionPersonalHelper.narrow(
    super._this_object(orb));
  }


} // class GestionPersonalPOA
