package sop_corba;

/**
* sop_corba/GestionPersonalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public final class GestionPersonalHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionPersonal value = null;

  public GestionPersonalHolder ()
  {
  }

  public GestionPersonalHolder (sop_corba.GestionPersonal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionPersonalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionPersonalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionPersonalHelper.type ();
  }

}
