package sop_corba.GestionPersonalPackage;


/**
* sop_corba/GestionPersonalPackage/personalDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public final class personalDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String tipo_id = null;
  public int id = (int)0;
  public String nombreCompleto = null;
  public String ocupacion = null;
  public String usuario = null;
  public String clave = null;

  public personalDTO ()
  {
  } // ctor

  public personalDTO (String _tipo_id, int _id, String _nombreCompleto, String _ocupacion, String _usuario, String _clave)
  {
    tipo_id = _tipo_id;
    id = _id;
    nombreCompleto = _nombreCompleto;
    ocupacion = _ocupacion;
    usuario = _usuario;
    clave = _clave;
  } // ctor

 // class personalDTO

  public String getTipo_id() {
    return this.tipo_id;
  }

  public void setTipo_id(String tipo_id) {
    this.tipo_id = tipo_id;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getNombreCompleto() {
    return this.nombreCompleto;
  }

  public void setNombreCompleto(String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
  }

  public String getOcupacion() {
    return this.ocupacion;
  }

  public void setOcupacion(String ocupacion) {
    this.ocupacion = ocupacion;
  }

  public String getUsuario() {
    return this.usuario;
  }

  public void setUsuario(String usuario) {
    this.usuario = usuario;
  }

  public String getClave() {
    return this.clave;
  }

  public void setClave(String clave) {
    this.clave = clave;
  }

  @Override
  public String toString() {
    return "{" +
      " tipo_id='" + getTipo_id() + "'" +
      ", id='" + getId() + "'" +
      ", nombreCompleto='" + getNombreCompleto() + "'" +
      ", ocupacion='" + getOcupacion() + "'" +
      ", usuario='" + getUsuario() + "'" +
      ", clave='" + getClave() + "'" +
      "}";
  }

}
  
