package sop_corba.GestionPersonalPackage;

/**
* sop_corba/GestionPersonalPackage/personalDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_personal.idl
* martes 8 de febrero de 2022 09:54:12 AM COT
*/

public final class personalDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionPersonalPackage.personalDTO value = null;

  public personalDTOHolder ()
  {
  }

  public personalDTOHolder (sop_corba.GestionPersonalPackage.personalDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionPersonalPackage.personalDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionPersonalPackage.personalDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionPersonalPackage.personalDTOHelper.type ();
  }

}
